# Generated by Django 6.0.5 on 2026-05-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
